### ISSUE TITLE
JustTrains Voyager 

### ISSUE THREAD

**Issue by GazTheDev** [jrmckenzie/RSSwapTool#2]
Just something that can be added, possibly, The JT voyager for the DTG one included with the WCML :). Just an idea. Tried doing it myself but not to good with python :).

**Comment by jrmckenzie** [comment]
Hi Gaz thanks for your feedback, that's a good idea, is that DTG WCML South (Euston to Birmingham or wherever) you're asking about? I just bought it in a sale a couple of weeks ago, so I'll investigate. I'm no dev and fairly new to python myself, just teaching myself with this project so excuse the code mess, it's evolved from just swapping AP Mk1 coaches to this without any clear goals.

**Comment by jrmckenzie** [comment]
This should be possible - although there is no Avanti livery in the JT voyager pack so it would probably be a swap for a Virgin  livery (flowing silk?), unless there is a good third party Avanti reskin for the JT voyagers you can recommend? I'll work on adding details of the DTG WCMLS 350 and 377 EMUs too, so these are swapped for the AP enhanced versions like the ones bundled with other routes are. The most time consuming part is always mapping over the destinations.

**Comment by GazTheDev** [comment]
Hi Jr. 

Can't think of an avanti livery but can ask around for sure. and get back to you. 

I'm a programmer myself but of a web programmer PHP, MYSQL, Javascript etc... But Python is something I want to learn at somepoint :).

**Comment by jrmckenzie** [comment]
For now, it can swap DTG WCML-South Avanti Voyagers for JT Ex-VT NS Voyagers. DTG WCML-South 350s, 377s, FSAs and FTAs have been added to the database of swaps too. With your background I imagine python will be easy to learn the ways of. I dabbled in Perl, PHP and MySQL in a previous career that ended the best part of 20 years ago, python is not too mindbending for a next step, especially with help from IDEs like PyCharm free for community open-source use.

**Comment by GazTheDev** [comment]
Ahh yeah taking a look at PyCharm now. Will have a look into it further! :). Glad to see WCML stuff added :)

**Comment by jrmckenzie** [comment]
I've revised it again (both on Github and Dropbox) and bumped the version to v0.14a. It will now also replace the other DTG Class 220 Pack (Cross Country) and DTG North Wales Coast Class 221 (Virgin). It now replaces with the WCML-South Class 221s with a reskinned JT Class 221 - for which the following is required: https://semaphoresim.com/file/104-meridianvoyager-advanced-2019-overhaul/ Unfortunately it's still not a like-for-like Avanti livery replacement but a step in the right direction until something better comes along.

**Comment by GazTheDev** [comment]
Perfect. 

I was actually going to ask - if you want I can put this on my new website launching soon. It's a TrainSim website focussing in on guides and tutorials and based on my YouTube channel. 

The site is built from the ground up so anything is possible really. 

Let me know if your interested - I'm going to do a video on it anyway but wondered if you'd like it on my website :).

**Comment by jrmckenzie** [comment]
Hi Gaz it's kind of you to offer, that would be nice of you. Provided what you do with it complies with the GPL v3 license and includes a link to this github repository somewhere you're free to host it there, and I hope it's of some use. I can't promise providing much support for it. The latest version (as of today) is v0.1b.

**Comment by jrmckenzie** [comment]
Best wishes with your website, please feel free to drop me an email with the details when it's up and running! I am closing this DTG WCMLS Voyager issue as there is now a JT swap option added for this (albeit one relying on a third party reskin that doesn't completely correspond with the DTG version).
